MODEL_NAME := imx6ull_100ask_pro
MODEL_OUTPUT_TAG := demo_console
MODEL_PUBLIC_APPS := app_demo
MODEL_PRIVATE_APPS := detect_gps

MODEL_THIRD_PARTY_BUILDROOT_DIR := $(ROOT_DIR)third_party/buildroot/buildroot-2020.02
MODEL_THIRD_PARTY_KERNEL_DIR := $(ROOT_DIR)third_party/linux/imx-linux4.9.88
MODEL_THIRD_PARTY_UBOOT_DIR := $(ROOT_DIR)third_party/uboot/imx-uboot2017.03

MODEL_KERNEL_DTS_NAME := 100ask_imx6ull-14x14
MODEL_KERNEL_INTREE_DTS_NAMES := 100ask_imx6ull_mini 100ask_myir_imx6ull_mini
MODEL_KERNEL_CUSTOM_DTS_FILES := \
	$(MODEL_KERNEL_DTS_NAME).dts
MODEL_KERNEL_CUSTOM_DTS_PATHS := \
	$(foreach dts,$(MODEL_KERNEL_CUSTOM_DTS_FILES),$(BOARD_LINUX_DTS_DIR)/$(dts))

MODEL_TOOLCHAIN_PREFIX := arm-buildroot-linux-gnueabihf
MODEL_TOOLCHAIN_HOST_SUBDIR := host
MODEL_TOOLCHAIN_BINDIR_SUBDIR := $(MODEL_TOOLCHAIN_HOST_SUBDIR)/bin
MODEL_TOOLCHAIN_SYSROOT_SUBDIR := $(MODEL_TOOLCHAIN_HOST_SUBDIR)/$(MODEL_TOOLCHAIN_PREFIX)/sysroot

MODEL_FEATURE_WIFI := 1
MODEL_FEATURE_QT := 1
MODEL_FEATURE_LVGL := 1
MODEL_FEATURE_MODEM := 1

MODEL_APP_CPPFLAGS := \
	-DCONFIG_MODEL_IMX6ULL_100ASK_PRO=1 \
	-DCONFIG_FEATURE_WIFI=$(MODEL_FEATURE_WIFI) \
	-DCONFIG_FEATURE_QT=$(MODEL_FEATURE_QT) \
	-DCONFIG_FEATURE_LVGL=$(MODEL_FEATURE_LVGL) \
	-DCONFIG_FEATURE_MODEM=$(MODEL_FEATURE_MODEM)

MODEL_BUILDROOT_EXTRA_CONFIGS := \
	$(BOARD_DIR)/buildroot/configs/sdk_compat.config
